export const BusPark = [
  "Kimironko",
  "Nyabugogo",
  "Kacyiru",
  "Remera",
  "Nyamirambo",
  "Gikondo",
  "Kanombe",
  "Nyanza",
  "Muhima",
  "Gisozi",
  "Kabeza",
  "Kimisagara",
  "Gatsata",
  "Kagugu",
  "kinyinya",
  "Karama"
];

export const BusStops = [
  "Batsinda",
  "Biryogo",
  "Busanza",
  "Busanza Market",
  "Downtown",
  "Free Zone",
  "Gahanga",
  "Gahanga Bus Park",
  "Gahanga Health Center",
  "Gahanga Trading Centre",
  "Gikondo",
  "Gikondo Free Zone",
  "Gikondo Gitega",
  "Gikondo Industrial Area",
  "Gikondo Merez",
  "Gisozi",
  "Gisovu",
  "Kimihurura",
  "Gishushu",
  "Kabuye",
  "Kabeza",
  "Kagugu",
  "Karama",
  "Kibagabaga",
  "Kimironko",
  "Kimisagara",
  "Kimisange",
  "Kinyinya",
  "Kiyovu",
  "Kizito",
  "Kizito",
  "Kanombe",
  "Kacyiru",
  "Kizito",
  "Masaka",
  "Mulindi",
  "Muhima",
  "Ndera",
  "Nyanza Kicukiro",
  "Nyabugogo",
  "Nyamirambo",
  "Nyacyonga",
  "Nyarugenge",
  "Nyarugunga",
  "Nyarutarama",
  "Rebero",
  "Remera",
  "Rusororo",
  "Ruyenzi",
  "Zindiro",
];

export const KigaliBusJourney = [
  {
    id: "JF937H950-248802-DNDNJ",
    plateNumber: "RAC843KG",
    numberOfSeats: 35,
    from: "Zindiro",
    to: "Kimironko",
    busType: "Royal",
    departureAt: "8:00 am",
    arrivalTime: "9:20 am",
    price: "380"
  },
  {
    id: "JF937H950-248803-DNDNK",
    plateNumber: "RAC844KG",
    numberOfSeats: 35,
    from: "Kimironko",
    to: "Downtown",
    busType: "Royal",
    departureAt: "9:30 am",
    arrivalTime: "10:00 am",
    price: "300"
  },
  {
    id: "JF937H950-248804-DNDNL",
    plateNumber: "RAC845KG",
    numberOfSeats: 35,
    from: "Downtown",
    to: "Kicukiro",
    busType: "Kigali Bus Service",
    departureAt: "10:15 am",
    arrivalTime: "11:00 am",
    price: "350"
  },
  {
    id: "JF937H950-248805-DNDNM",
    plateNumber: "RAC846KG",
    numberOfSeats: 35,
    from: "Kicukiro",
    to: "Nyabugogo",
    busType: "Royal",
    departureAt: "11:15 am",
    arrivalTime: "12:00 pm",
    price: "320"
  },
  {
    id: "JF937H950-248806-DNDNN",
    plateNumber: "RAC847KG",
    numberOfSeats: 35,
    from: "Nyabugogo",
    to: "Gikondo",
    busType: "Kigali Bus Service",
    departureAt: "12:15 pm",
    arrivalTime: "12:45 pm",
    price: "310"
  },
  {
    id: "JF937H950-248808-DNDNP",
    plateNumber: "RAC849KG",
    numberOfSeats: 35,
    from: "Kanombe",
    to: "Remera",
    busType: "Kigali Bus Service",
    departureAt: "2:00 pm",
    arrivalTime: "2:40 pm",
    price: "340"
  },
  {
    id: "JF937H950-248809-DNDNQ",
    plateNumber: "RAC850KG",
    numberOfSeats: 35,
    from: "Nyabugogo",
    to: "Nyamirambo",
    busType: "Royal",
    departureAt: "3:00 pm",
    arrivalTime: "3:30 pm",
    price: "325"
  },
  {
    id: "JF937H950-248810-DNDNR",
    plateNumber: "RAC851KG",
    numberOfSeats: 35,
    from: "Nyamirambo",
    to: "Downtown",
    busType: "Kigali Bus Service",
    departureAt: "4:00 pm",
    arrivalTime: "4:30 pm",
    price: "310"
  },

  {
    id: "JF937H950-248807-DNDNO",
    plateNumber: "RAC848KG",
    numberOfSeats: 35,
    from: "Gikondo",
    to: "Nyabugogo",
    busType: "Royal",
    departureAt: "1:00 pm",
    arrivalTime: "1:30 pm",
    price: "310"
  },
  {
    id: "JF937H950-248811-DNDNS",
    plateNumber: "RAC852KG",
    numberOfSeats: 35,
    from: "Nyabugogo",
    to: "Kicukiro",
    busType: "Royal",
    departureAt: "5:00 pm",
    arrivalTime: "5:30 pm",
    price: "350"
  },
  {
    id: "JF937H950-248812-DNDNT",
    plateNumber: "RAC853KG",
    numberOfSeats: 35,
    from: "Nyarutarama",
    to: "Downtown",
    busType: "Kigali Bus Service",
    departureAt: "6:00 pm",
    arrivalTime: "6:30 pm",
    price: "340"
  },
  {
    id: "JF937H950-248813-DNDNU",
    plateNumber: "RAC854KG",
    numberOfSeats: 35,
    from: "Nyabugogo",
    to: "Gatsata",
    busType: "Royal",
    departureAt: "7:00 pm",
    arrivalTime: "7:45 pm",
    price: "330"
  },
  {
    id: "JF937H950-248814-DNDNV",
    plateNumber: "RAC855KG",
    numberOfSeats: 35,
    from: "Remera",
    to: "Kabuga",
    busType: "Kigali Bus Service",
    departureAt: "8:00 pm",
    arrivalTime: "8:45 pm",
    price: "520"
  },
  {
    id: "JF937H950-248815-DNDNW",
    plateNumber: "RAC856KG",
    numberOfSeats: 35,
    from: "Kimironko",
    to: "Kabuga",
    busType: "Royal",
    departureAt: "9:00 pm",
    arrivalTime: "9:30 pm",
    price: "310"
  },
  {
    id: "JF937H950-248816-DNDNX",
    plateNumber: "RAC857KG",
    numberOfSeats: 35,
    from: "Remera",
    to: "Nyabugogo",
    busType: "Kigali Bus Service",
    departureAt: "10:00 pm",
    arrivalTime: "10:30 pm",
    price: "320"
  },
  {
    id: "JF937H950-248817-DNDNY",
    plateNumber: "RAC858KG",
    numberOfSeats: 35,
    from: "Nyabugogo",
    to: "Masaka",
    busType: "Royal",
    departureAt: "11:00 pm",
    arrivalTime: "11:30 pm",
    price: "330"
  },
  {
    id: "JF937H950-248818-DNDNZ",
    plateNumber: "RAC859KG",
    numberOfSeats: 35,
    from: "Kimironko",
    to: "Rebero",
    busType: "Kigali Bus Service",
    departureAt: "12:00 am",
    arrivalTime: "12:30 am",
    price: "340"
  },
  {
    id: "JF937H950-248819-DNDOA",
    plateNumber: "RAC860KG",
    numberOfSeats: 35,
    from: "Rebero",
    to: "Kinyinya",
    busType: "Royal",
    departureAt: "7:30 am",
    arrivalTime: "8:15 am",
    price: "325"
  },
  {
    id: "JF937H950-248820-DNDOB",
    plateNumber: "RAC861KG",
    numberOfSeats: 35,
    from: "Nyabugogo",
    to: "Kimisagara",
    busType: "Kigali Bus Service",
    departureAt: "8:30 am",
    arrivalTime: "9:00 am",
    price: "310"
  },
]
