export const BusPark = [
  "Kimironko",
  "Nyabugogo",
  "Kacyiru",
  "Remera",
  "Kicukiro Central",
  "Nyamirambo",
  "Gikondo",
  "Kanombe",
  "Nyanza",
  "Muhima",
  "Gisozi",
  "Kabeza",
  "Kimisagara",
  "Gatsata",
];

export const BusStops = [
  "Batsinda",
  "Biryogo",
  "Busanza",
  "Busanza Market",
  "Downtown",
  "Free Zone",
  "Gahanga",
  "Gahanga Bus Park",
  "Gahanga Health Center",
  "Gahanga Trading Centre",
  "Gikondo",
  "Gikondo Free Zone",
  "Gikondo Gitega",
  "Gikondo Industrial Area",
  "Gikondo Merez",
  "Gisozi",
  "Gisozi Genocide Memorial",
  "Gisozi Memorial Site",
  "Gisozi Modern Market",
  "Gisozi Museum",
  "Gisozi Sector Office",
  "Gisozi Technical School",
  "Gisovu",
  "Kimihurura",
  "Gishushu",
  "Gishushu Remera",
  "Kabuye",
  "Kabuye Industrial Park",
  "Kabuye Petrol Station",
  "Kabeza",
  "Kabeza Kanombe",
  "Kabeza Kanombe Centre",
  "Kabeza Market",
  "Kabeza Primary School",
  "Kibagabaga",
  "Kibagabaga Center",
  "Kibagabaga Commercial Centre",
  "Kibagabaga Hospital",
  "Kibagabaga Hospital",
  "Kibagabaga Roundabout",
  "Kimironko",
  "Kimironko Bus Park",
  "Kimironko Health Center",
  "Kimironko Market",
  "Kimironko Modern Market",
  "Kimironko Nyarutarama",
  "Kimironko Park",
  "Kimironko Police",
  "Kimironko Police Station",
  "Kimironko Sector Office",
  "Kimironko Village",
  "Kimisagara",
  "Kimisagara Primary School",
  "Kimisange",
  "Kicukiro",
  "Kicukiro Business District",
  "Kicukiro Centre",
  "Kicukiro Centre Market",
  "Kicukiro District",
  "Kicukiro IPRC",
  "Kicukiro IPRC South",
  "Kicukiro Trading Centre",
  "Kinyinya",
  "Kinyinya Commercial Center",
  "Kinyinya Gikondo",
  "Kinyinya Green Hills",
  "Kinyinya MTN Center",
  "Kinyinya Petrol Station",
  "Kinyinya Police",
  "Kinyinya Sector Office",
  "Kinyinya Simba",
  "Kiyovu",
  "Kizito",
  "Kizito",
  "Kanombe",
  "Kanombe Airport",
  "Kanombe Airport Road",
  "Kanombe Centre",
  "Kanombe Health Center",
  "Kanombe Military",
  "Kanombe Military Academy",
  "Kanombe Military Hospital",
  "Kacyiru",
  "Kacyiru King Faisal Hospital",
  "Kacyiru Main Road",
  "Kacyiru Ministry of Health",
  "Kacyiru Office of Ombudsman",
  "Kacyiru Police Hospital",
  "Kacyiru President’s Office",
  "Kacyiru Rwanda Development Board",
  "Kacyiru Rwanda Revenue Authority",
  "Kinyinya Commercial Center",
  "Kinyinya Sector Office",
  "Kinyinya Simba",
  "Kizito",
  "Masaka",
  "Masaka Hospital",
  "Masaka Primary School",
  "Masaka Trading Center",
  "Magerwa",
  "Magerwa Gikondo",
  "Mulindi",
  "Muhima",
  "Ndera",
  "Ndera Bus Stop",
  "Ndera Health Center",
  "Ndera Kabuye",
  "Ndera Primary School",
  "Ndera Rwanda",
  "Ndera Rusororo",
  "Nyanza",
  "Nyanza Kicukiro",
  "Nyabugogo",
  "Nyabugogo Bus Terminal",
  "Nyabugogo East",
  "Nyabugogo KBS",
  "Nyabugogo Main Station",
  "Nyabugogo Market",
  "Nyabugogo Modern Market",
  "Nyabugogo St. Famille",
  "Nyabugogo Terminal",
  "Nyamirambo",
  "Nyamirambo Business Center",
  "Nyamirambo Maison de Jeunes",
  "Nyamirambo Maison des Jeunes",
  "Nyamirambo Mosque",
  "Nyamirambo Nyakabanda",
  "Nyamirambo Stade",
  "Nyacyonga",
  "Nyacyonga Main Road",
  "Nyarugenge",
  "Nyarugenge Market",
  "Nyarugunga",
  "Nyarutarama",
  "Rebero",
  "Rubirizi",
  "Ruhengeri Bus Park",
  "Rwanda National Police HQ",
  "Rwandex",
  "Rusororo",
  "Ruyenzi",
  "Zindiro",
];

export const KigaliBusJourney = [
  {
    id: "JF937H950-248802-DNDNJ",
    plateNumber: "RAC843KG",
    numberOfSeats: 35,
    from: "Zindiro",
    to: "Kimironko",
    busType: "Royal",
    departureAt: "8:00 am",
    arrivalTime: "9:20 am",
    price: "380"
  },
  {
    id: "JF937H950-248803-DNDNK",
    plateNumber: "RAC844KG",
    numberOfSeats: 35,
    from: "Kimironko",
    to: "Downtown",
    busType: "Royal",
    departureAt: "9:30 am",
    arrivalTime: "10:00 am",
    price: "300"
  },
  {
    id: "JF937H950-248804-DNDNL",
    plateNumber: "RAC845KG",
    numberOfSeats: 35,
    from: "Downtown",
    to: "Kicukiro",
    busType: "Kigali Bus Service",
    departureAt: "10:15 am",
    arrivalTime: "11:00 am",
    price: "350"
  },
  {
    id: "JF937H950-248805-DNDNM",
    plateNumber: "RAC846KG",
    numberOfSeats: 35,
    from: "Kicukiro",
    to: "Nyabugogo",
    busType: "Royal",
    departureAt: "11:15 am",
    arrivalTime: "12:00 pm",
    price: "320"
  },
  {
    id: "JF937H950-248806-DNDNN",
    plateNumber: "RAC847KG",
    numberOfSeats: 35,
    from: "Nyabugogo",
    to: "Gikondo",
    busType: "Kigali Bus Service",
    departureAt: "12:15 pm",
    arrivalTime: "12:45 pm",
    price: "310"
  },
  {
    id: "JF937H950-248808-DNDNP",
    plateNumber: "RAC849KG",
    numberOfSeats: 35,
    from: "Kanombe",
    to: "Remera",
    busType: "Kigali Bus Service",
    departureAt: "2:00 pm",
    arrivalTime: "2:40 pm",
    price: "340"
  },
  {
    id: "JF937H950-248809-DNDNQ",
    plateNumber: "RAC850KG",
    numberOfSeats: 35,
    from: "Nyabugogo",
    to: "Nyamirambo",
    busType: "Royal",
    departureAt: "3:00 pm",
    arrivalTime: "3:30 pm",
    price: "325"
  },
  {
    id: "JF937H950-248810-DNDNR",
    plateNumber: "RAC851KG",
    numberOfSeats: 35,
    from: "Nyamirambo",
    to: "Downtown",
    busType: "Kigali Bus Service",
    departureAt: "4:00 pm",
    arrivalTime: "4:30 pm",
    price: "310"
  },

  {
    id: "JF937H950-248807-DNDNO",
    plateNumber: "RAC848KG",
    numberOfSeats: 35,
    from: "Gikondo",
    to: "Nyabugogo",
    busType: "Royal",
    departureAt: "1:00 pm",
    arrivalTime: "1:30 pm",
    price: "310"
  },
  {
    id: "JF937H950-248811-DNDNS",
    plateNumber: "RAC852KG",
    numberOfSeats: 35,
    from: "Nyabugogo",
    to: "Kicukiro",
    busType: "Royal",
    departureAt: "5:00 pm",
    arrivalTime: "5:30 pm",
    price: "350"
  },
  {
    id: "JF937H950-248812-DNDNT",
    plateNumber: "RAC853KG",
    numberOfSeats: 35,
    from: "Nyarutarama",
    to: "Downtown",
    busType: "Kigali Bus Service",
    departureAt: "6:00 pm",
    arrivalTime: "6:30 pm",
    price: "340"
  },
  {
    id: "JF937H950-248813-DNDNU",
    plateNumber: "RAC854KG",
    numberOfSeats: 35,
    from: "Nyabugogo",
    to: "Gatsata",
    busType: "Royal",
    departureAt: "7:00 pm",
    arrivalTime: "7:45 pm",
    price: "330"
  },
  {
    id: "JF937H950-248814-DNDNV",
    plateNumber: "RAC855KG",
    numberOfSeats: 35,
    from: "Remera",
    to: "Kabuga",
    busType: "Kigali Bus Service",
    departureAt: "8:00 pm",
    arrivalTime: "8:45 pm",
    price: "520"
  },
  {
    id: "JF937H950-248815-DNDNW",
    plateNumber: "RAC856KG",
    numberOfSeats: 35,
    from: "Kimironko",
    to: "Kabuga",
    busType: "Royal",
    departureAt: "9:00 pm",
    arrivalTime: "9:30 pm",
    price: "310"
  },
  {
    id: "JF937H950-248816-DNDNX",
    plateNumber: "RAC857KG",
    numberOfSeats: 35,
    from: "Remera",
    to: "Nyabugogo",
    busType: "Kigali Bus Service",
    departureAt: "10:00 pm",
    arrivalTime: "10:30 pm",
    price: "320"
  },
  {
    id: "JF937H950-248817-DNDNY",
    plateNumber: "RAC858KG",
    numberOfSeats: 35,
    from: "Nyabugogo",
    to: "Masaka",
    busType: "Royal",
    departureAt: "11:00 pm",
    arrivalTime: "11:30 pm",
    price: "330"
  },
  {
    id: "JF937H950-248818-DNDNZ",
    plateNumber: "RAC859KG",
    numberOfSeats: 35,
    from: "Kimironko",
    to: "Rebero",
    busType: "Kigali Bus Service",
    departureAt: "12:00 am",
    arrivalTime: "12:30 am",
    price: "340"
  },
  {
    id: "JF937H950-248819-DNDOA",
    plateNumber: "RAC860KG",
    numberOfSeats: 35,
    from: "Rebero",
    to: "Kinyinya",
    busType: "Royal",
    departureAt: "7:30 am",
    arrivalTime: "8:15 am",
    price: "325"
  },
  {
    id: "JF937H950-248820-DNDOB",
    plateNumber: "RAC861KG",
    numberOfSeats: 35,
    from: "Nyabugogo",
    to: "Kimisagara",
    busType: "Kigali Bus Service",
    departureAt: "8:30 am",
    arrivalTime: "9:00 am",
    price: "310"
  },
]
